app/urls.py
from django.urls import path

from app.views import (
    IndexView,
    TagListView,
    TaskCreateView,
    TaskStatusUpdateView,
    TaskUpdateView,
    TaskDeleteView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "task/<int:pk>/complete/",
        TaskStatusUpdateView.as_view(),
        name="task-complete-undo",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

app_name = "app"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

app/models.py
from django.db import models


class Task(models.Model):
    content = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    done = models.BooleanField(default=False)
    tags = models.ManyToManyField("Tag", blank=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.content}"


class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return f"{self.name}"

app/forms.py
from django import forms

from app.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = "__all__"


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = "__all__"

app/views.py
from django.urls import reverse_lazy
from django.views import generic

from app.forms import TaskForm, TagForm
from app.models import Task, Tag


class IndexView(generic.ListView):
    model = Task
    template_name = "app/index.html"
    context = {"tasks": Task.objects.all()}


class TagListView(generic.ListView):
    model = Tag
    template_name = "app/tag_list.html"


class TagCreateView(generic.CreateView):
    model = Tag
    form_class = TagForm
    template_name = "app/tag_form.html"
    success_url = reverse_lazy("app:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("app:tag-list")


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    template_name = "app/task_form.html"
    success_url = reverse_lazy("app:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("app:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("app:index")


class TaskStatusUpdateView(generic.UpdateView):
    model = Task
    fields = ["done"]
    success_url = reverse_lazy("app:index")

templates/app/index.html
{% extends "base.html" %}

{% block content %}
    <h1>
      TODO List
    <a href="{% url 'app:task-create' %}" class="btn btn-primary link-to-page">
      Add task
    </a>
    </h1>
  {% for task in task_list %}
    <h2 class="task-content">
      {{ task.content }}
      {% if task.done %}
        <span style="color:green;" class="task-status">
          Done
        </span>
        <a href="{% url 'app:task-complete-undo' task.id %}" class="btn btn-warning link-to-page complete">
          Undo
        </a>

      {% else %}
        <span style="color:red;" class="task-status">
          Not Done
        </span>
        <a href="{% url 'app:task-complete-undo' task.id %}" class="btn btn-success link-to-page complete">
          Complete
        </a>
      {% endif %}
    </h2>
    <p style="font-size: 15px">
      Created at: {{ task.created_at }}
    </p>
    <h3>
      Tags:
      {% for tag in task.tags.all %}
        <a href="" class="btn btn-default link-to-page">
          {{ tag.name }}
        </a>
      {% endfor %}
    </h3>
    <a href="{% url 'app:task-update' task.id %}" class="btn btn-success link-to-page">
      Update task details
    </a>
    <a href="{% url 'app:task-delete' task.id %}" class="btn btn-danger link-to-page">
      Delete task
    </a>
    <hr class="solid divider">
    <br>
  {% endfor %}
{% endblock %}

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section>
    <h1>Delete tag "{{ tag.name }}"?</h1>
    <form action="" method="post">
      {% csrf_token %}
  
      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </section>
{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>

{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
      Tags
    <a href="{% url 'app:tag-create' %}" class="btn btn-primary link-to-page">
      Add tag
    </a>
    </h1>
  <table class="table">
    <tr>
      <th style="text-align: center">Tag</th>
      <th></th>
      <th></th>
    </tr>
    {% for tag in tag_list %}
      <tr>
        <td class="tag-table">{{ tag.name }}</td>
        <td>
          <a href="{% url 'app:tag-update' tag.id %}" class="btn btn-primary link-to-page">
            Update
          </a>
        </td>
        <td>
          <a href="{% url 'app:tag-delete' tag.id %}" class="btn btn-danger link-to-page">
            Delete
          </a>
        </td>
      </tr>
    {% endfor %}
{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <section>
    <h1>Delete {{ task.content }}?</h1>
    <form action="" method="post">
      {% csrf_token %}
  
      <input type="submit" value="Yes" class="btn btn-danger">
    </form>
  </section>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <section class="main-content">
    <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
    </form>
  </section>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  {% block title %}<title>To-Do List</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu"
    crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css'  %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">

      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock %}

    </div>
    <div class="col-sm-10 ">

      {% block content %}{% endblock %}


    </div>
  </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li class="list-group-item"><a href="{% url 'app:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'app:tag-list' %}">Tags</a></li>
</ul>